### ISSUE TITLE
SchemaTypes.Boolean 

### ISSUE THREAD

**Issue by ghostwalkerj** [andreww2012/mongoose-zod#13]
I have been trying to debug this for a week.  Using sveltekit and mongoose 6.6.5 and for some schemas, I am getting this runtime error in the browser

`TypeError: Cannot read properties of undefined (reading 'Boolean')
`
From this line in:
```Typescript
var MongooseZodBoolean = class extends M.SchemaTypes.Boolean {
  constructor() {
    super(...arguments);
    this.cast = noCastFn;
  }
};
```

I thought perhaps a mismatch dependency, but using the same version libs as mongoose-zod.  I can't figure out what is making it through this error only on some schemas.

**Comment by ghostwalkerj** [comment]
I think this has something to do with the polyfills.  I am using sveltekit and vite.

**Comment by andreww2012** [comment]
Hey, sorry for the late answer.
This might be a sign of duplicate dependency (probably there's a `default` property on `M`), but it's a bit difficult to be sure without knowing the exact dependencies and the way you're using the library. Please kindly provide [a minimal reproduction](https://antfu.me/posts/why-reproductions-are-required) and I might be able to help you more substantively. Closing this for now.
