### ISSUE TITLE
refs?

### ISSUE THREAD

**Issue by adrianwiechec-at-optilyz** [andreww2012/mongoose-zod#5]
A question: how do you define refs (https://mongoosejs.com/docs/populate.html) with mongoose-zod? I know I can set the type of the relationship field to `mongooseZodCustomType("ObjectId")`, but how do I specify the related model?

**Comment by andreww2012** [comment]
You can define a ref using type options, [in two ways](/andreww2012/mongoose-zod#what-is-the-recommended-way-of-defining-type-options):

```ts
import {mongooseZodCustomType, toMongooseSchema} from 'mongoose-zod';
import {z} from 'zod';

const UserZod = z.object({
  // Option 1: use `mongooseTypeOptions()`
  friends: mongooseZodCustomType('ObjectId').mongooseTypeOptions({
    ref: 'User',
  }),
});

const UserSchema = toMongooseSchema(
  UserZod.mongoose({
    // Option 2: use `typeOptions: { ... }
    typeOptions: {
      friends: {ref: 'User'},
    },
  }),
);
```

**Comment by adrianwiechec-at-optilyz** [comment]
Thanks!
